/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as PreventivoRouteImport } from './routes/preventivo'
import { Route as LavoraConNoiRouteImport } from './routes/lavora-con-noi'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'

const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivoRoute = PreventivoRouteImport.update({
  id: '/preventivo',
  path: '/preventivo',
  getParentRoute: () => rootRouteImport,
} as any)
const LavoraConNoiRoute = LavoraConNoiRouteImport.update({
  id: '/lavora-con-noi',
  path: '/lavora-con-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/preventivo': typeof PreventivoRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/preventivo': typeof PreventivoRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/preventivo': typeof PreventivoRoute
  '/servizi': typeof ServiziRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/lavora-con-noi'
    | '/preventivo'
    | '/servizi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/lavora-con-noi'
    | '/preventivo'
    | '/servizi'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/lavora-con-noi'
    | '/preventivo'
    | '/servizi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  LavoraConNoiRoute: typeof LavoraConNoiRoute
  PreventivoRoute: typeof PreventivoRoute
  ServiziRoute: typeof ServiziRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivo': {
      id: '/preventivo'
      path: '/preventivo'
      fullPath: '/preventivo'
      preLoaderRoute: typeof PreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavora-con-noi': {
      id: '/lavora-con-noi'
      path: '/lavora-con-noi'
      fullPath: '/lavora-con-noi'
      preLoaderRoute: typeof LavoraConNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  LavoraConNoiRoute: LavoraConNoiRoute,
  PreventivoRoute: PreventivoRoute,
  ServiziRoute: ServiziRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
